"""empty message

Revision ID: 0822b8131bbe
Revises: 20140f191cff
Create Date: 2025-05-12 18:26:18.278974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0822b8131bbe'
down_revision = '20140f191cff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.INTEGER(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###
