"""empty message

Revision ID: 20140f191cff
Revises: 0c5f320e29a9
Create Date: 2025-05-12 17:04:19.458816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20140f191cff'
down_revision = '0c5f320e29a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    # ### end Alembic commands ###
